import Link from "next/link";
import { ArrowRight, ChartNoAxesCombined, Leaf, LockKeyhole, Sprout, Wallet } from "lucide-react";

const points = ["A gentle daily money check-in", "Your categories, your language", "Private data stored in your browser"];
const featureCards = [
  { Icon: ChartNoAxesCombined, title: "Notice the patterns", text: "Simple views reveal the rhythms hiding in everyday spending." },
  { Icon: Sprout, title: "Choose with care", text: "Build awareness first; better choices tend to follow." },
  { Icon: LockKeyhole, title: "Keep it personal", text: "Your demo data stays in your browser, under your control." },
];

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-[#f7f3ea] text-[#203128]">
    <div className="paper-grid absolute inset-0 -z-10 opacity-80" />
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6 lg:px-8"><Link href="/" className="flex items-center gap-2 text-xl font-bold"><span className="grid size-10 place-items-center rounded-full bg-[#3e6b50] text-white"><Leaf className="size-5" /></span> spendwise</Link><div className="flex items-center gap-3 text-sm font-semibold"><Link href="/login" className="px-3 py-2 text-[#3e6b50]">Log in</Link><Link href="/register" className="rounded-full bg-[#203128] px-5 py-2.5 text-white transition hover:bg-[#3e6b50]">Begin gently</Link></div></nav>
    <section className="mx-auto grid max-w-6xl gap-14 px-6 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pb-28 lg:pt-24"><div className="max-w-2xl"><p className="eyebrow flex items-center gap-2"><Sprout className="size-4" /> a softer way to manage money</p><h1 className="mt-5 text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Make space for the life <em className="font-serif font-normal text-[#3e6b50]">behind</em> your spending.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#68756d]">SpendWise is a calm, personal place to notice where your money goes—without guilt, clutter, or complicated charts.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#c96c4b] px-6 py-3.5 font-bold text-white shadow-lg shadow-[#c96c4b]/20 transition hover:-translate-y-0.5 hover:bg-[#b95e40]">Create your space <ArrowRight className="size-4" /></Link><Link href="/login" className="inline-flex items-center justify-center rounded-full border border-[#d8d2c6] bg-white/70 px-6 py-3.5 font-bold text-[#3e6b50] transition hover:bg-white">Try the demo</Link></div><div className="mt-10 grid gap-3 text-sm text-[#526056]">{points.map((point) => <span key={point} className="flex items-center gap-3"><span className="grid size-6 place-items-center rounded-full bg-[#dce9dd] text-[#3e6b50]">✓</span>{point}</span>)}</div></div>
      <div className="relative mx-auto w-full max-w-md"><div className="absolute -right-12 -top-12 size-44 rounded-full bg-[#dce9dd] blur-2xl" /><div className="leaf-shadow relative rounded-[2rem] border border-[#e8e3d9] bg-[#fffdf8] p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-[#68756d]">This month, you&apos;ve kept</p><p className="mt-1 text-4xl font-semibold tracking-tight">₹1,24,800</p></div><span className="grid size-12 place-items-center rounded-2xl bg-[#dce9dd] text-[#3e6b50]"><Wallet /></span></div><div className="mt-7 rounded-2xl bg-[#203128] p-5 text-white"><div className="flex justify-between text-sm text-[#bdc9be]"><span>Little moments, added up</span><span>August</span></div><div className="mt-6 flex h-28 items-end gap-2">{[35,52,42,67,49,82,58,95].map((n,i)=><i key={i} className="flex-1 rounded-t-full bg-[#a8c3aa]" style={{height:`${n}%`,opacity:i===7?1:.55}} />)}</div></div><div className="mt-4 rounded-2xl border border-[#e8e3d9] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#68756d]">A small win</p><p className="mt-2 font-semibold">You spent 14% less on takeaways this month.</p><p className="mt-1 text-sm text-[#68756d]">That&apos;s room for what matters to you.</p></div></div><span className="absolute -bottom-6 -left-8 rounded-2xl bg-[#c96c4b] px-5 py-4 text-sm font-bold text-white shadow-xl">Slow progress is still progress.</span></div>
    </section>
    <section className="bg-[#203128] py-20 text-white"><div className="mx-auto grid max-w-6xl gap-8 px-6 md:grid-cols-3 lg:px-8">{featureCards.map(({ Icon, title, text })=><article key={title} className="rounded-3xl border border-white/10 bg-white/5 p-7"><Icon className="size-7 text-[#c9dfc9]" /><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-[#bdc9be]">{text}</p></article>)}</div></section>
  </main>;
}
